### ISSUE TITLE
500 Error on /merch/orders

### ISSUE THREAD

**Issue by steets250** [acmucsd/membership-portal#246]
Seems like the error is from the recent PR https://github.com/acmucsd/membership-portal/pull/237

```{
    "error": {
        "name": "TypeError",
        "message": "Cannot read property 'getPublicOrderMerchItem' of undefined",
        "httpCode": 500,
        "stack": "TypeError: Cannot read property 'getPublicOrderMerchItem' of undefined
            at MerchandiseItemOptionModel.getPublicOrderMerchItemOption (/app/build/models/MerchandiseItemOptionModel.js:36:29)
            at OrderItemModel.getPublicOrderItem (/app/build/models/OrderItemModel.js:20:33)
            at /app/build/models/OrderModel.js:28:93
            at Array.map (<anonymous>)
            at OrderModel.getPublicOrder (/app/build/models/OrderModel.js:28:78)
            at /app/build/api/controllers/MerchStoreController.js:162:63
            at Array.map (<anonymous>)
            at MerchStoreController.<anonymous> (/app/build/api/controllers/MerchStoreController.js:162:50)
            at Generator.next (<anonymous>)
            at fulfilled (/app/build/api/controllers/MerchStoreController.js:17:58)"
    }
}
```

**Comment by shravanhariharan2** [comment]
Fixed via. #245
